#!/usr/bin/env ruby

require_relative 'template'

if ARGV.size < 1 || ARGV.size > 2
  puts "USAGE: parse TEMPLATE [--trace]"
  abort
end

begin
  Template::Helpers.print(Template::Parser.new.parse(ARGV.first))
rescue Parslet::ParseFailed => e
  Template::Helpers.error(e, trace: ARGV[1] == "--trace")
end
